<div id="product_count_minicart_div" data-bind="scope: 'product_count_minicart_show'">

</div>

<script type="text/x-magento-init">
    {
         "#product_count_minicart_div": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "product_count_minicart_show": {
                            "component": "Training_ProductCountMinicartShow/js/product_count_minicart_show"
                        }
                    }
                }
            }
    }
</script>